const faqs = [
  {
    title: "How much does it cost to use the platform?",
    description: "Our platform is completely free to use. We believe in providing powerful tools to help you create professional resumes and portfolios without any cost."
  },
  {
    title: "How does the platform create my resume and portfolio?",
    description: "Our platform uses the information you provide to automatically generate a professional resume and portfolio. Simply enter your details, and our system does the rest, ensuring your documents are polished and ready to share."
  },
  {
    title: "Can I track the performance of my resume?",
    description: "Yes, our inbuilt analysis feature allows you to track total views, clicks, and conversion rates. This helps you understand how potential employers are interacting with your resume and portfolio."
  },
  {
    title: "Is my data secure on your platform?",
    description: "Absolutely. We use advanced encryption and security measures to protect your personal information and ensure that your data remains confidential and secure."
  },
  {
    title: "How can I share my resume or portfolio?",
    description: "You can share your resume or portfolio using the live link generated by our platform. Additionally, you have the option to download your resume as a PDF for offline sharing."
  },
  {
    title: "Can I update my resume or portfolio after creating it?",
    description: "Yes, you can easily update your resume or portfolio at any time through our CMS platform. Simply log in to your account, make the necessary changes, and your live link will reflect the updates instantly."
  },
  {
    title: "Do you offer customer support?",
    description: "Yes, our customer support team is available to assist you with any inquiries or issues. You can reach us via email or twitter."
  }
];


const FAQ = () => {
  return (
    <>
      <div className="landingPagePadx py-5 md:p-10" id="faqs">
        <div className="text-center uppercase app-text-primary">FAQs</div>
        <h2 className="text-center">Questions & Anwers</h2>
        <div className="flex justify-center mt-2">
          <div className="text-center text-gray-600 max-w-[70%] md:max-w-[60%] lg:max-w-[40%]">Any other questions? Reach out on twitter or mail. You will get answers withing a few hours.</div>
        </div>
        <div className=" flex justify-center">
          <div className=" join join-vertical w-full py-5 md:max-w-[80%] lg:max-w-[70%]">
            {faqs.map((faq, index) => (
              <div key={index} className="collapse collapse-arrow join-item border border-base-300">
                <input type="radio" name="my-accordion-4" />
                <div className="collapse-title text-xl font-medium">
                  {faq.title}
                </div>
                <div className="collapse-content text-gray-600">
                  <p>{faq.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  )
}

export default FAQ